[glossary]
api_key = "O/Op0Rw7wuc9n8fZe/41mdNlXPIbioSx78GGxrBtOSU/YpSTTmtPh2L80DI="

[deep_search]
api_key = "VkO5Fbh+EjdpwdjveS2bXTOTrJ885HFXGTUr0YqU2bcH+ugn/nc57jg56+8="
depth = 3

[deep_gemini]
api_key = "fB0Yx1uuWpFYF4Ky+dkpJsUBO2Okp+s9pqHS6fgjjOXhxdzqic9aSsLeTMA="

[proxy]
url = "http://127.0.0.1:7897"
